// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dvmghvscfwvigfpmzujx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR2bWdodnNjZnd2aWdmcG16dWp4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyOTkyNzcsImV4cCI6MjA2MTg3NTI3N30.PjpH1tRhybzsB7SIdukVdBZP2yklgFzjgYVPYtTb9Ks";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);